name: Artifact Test

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "Hello Min 👋" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-file
          path: hello.txt
