name: Playwright Test & Deploy Report

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ngăn GitHub Actions dùng token mặc định để tránh xung đột

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with HTML Report
        run: npx playwright test --reporter=html

      - name: Deploy HTML report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
