name: Playwright CI with Report & Notification

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

  notify:
    needs: test
    if: failure() # 🔥 Chỉ chạy khi test fail
    runs-on: ubuntu-latest

    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: report

      - name: Send Email if Test Failed
        uses: dawidd6/action-send-mail@v3
        with:
          to: minracaty@gmail.com
          subject: "❌ Playwright Test Failed!"
          body: |
            Các bài kiểm thử Playwright đã thất bại. 
            Xem báo cáo đính kèm hoặc tại: 
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: report/index.html
