name: Playwright Tests with Report
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
      - name: Test Report Summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Playwright Results
          path: playwright-report/results.json

  notify:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      # - name: Slack Alert
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "Playwright tests failed! Xem report tại: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    - name: Send Email Report
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        to: minracaty@gmail.com
        subject: "Playwright Test Report - ${{ github.repository }}"
        body: "Xem report đính kèm hoặc tại: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        attachments: playwright-report/index.html